// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.AccessCode2JsonTypes;

namespace Example
{

    public class AccessCode2
    {

        [JsonProperty("location")]
        public Location Location;
    }

}
