// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;

namespace iFormBuilderAPI
{
    public class RecordsCreator
    {
        public int PARENT_RECORD_ID { get; set; }
        public int PARENT_PAGE_ID { get; set; }
        public int PARENT_ELEMENT_ID { get; set; }
        public RecordsCreator()
        {
            RECORDS = new List<Record>();
        }
        public List<Record> RECORDS { get; set; }
    }

    /// <summary>
    /// Allows to create a record
    /// </summary>
    public class Record
    {
        public Record()
        {
            FIELDS = new List<Field>();
        }
        /// <summary>
        /// Parent Record ID (Use the Parent Table Id if this is a related Record)
        /// </summary>
        public long PARENT_PAGE_ID { get; set; }
        public List<Field> FIELDS { get; set; }
    }

    public class Field
    {
        public int ELEMENT_ID { get; set; }
        private Object _value;
        public Object VALUE
        {
            get
            {
                return _value == null ? "" : _value;
            }
            set { _value = value; }
        }

        private string _ext;
        public string EXT
        {
            get
            {
                return _ext == null ? "" : _ext;
            }
            set { _ext = value; }
        }
    }

    public class RecordFilter
    {
        public int OFFSET { get; set; }
        public int LIMIT { get; set; }
        public FilterKey SORT { get; set; }
        public FilterKeySort SORT_BY { get; set; }
        public List<Filter> Filters { get; set; }

        public enum FilterKey
        {
            ID, MODIFIED_DATE, MODIFIED_BY
        };

        public enum FilterKeySort
        {
            ASC,
            DESC
        };

    }
        public class Filter
        {
            public RecordFilter.FilterKey KEY { get; set; }
            public string CONDITION { get; set; }
            public string VALUE { get; set; }
        }

        public class AssignTO
        {
            public long ASSIGN { get; set; }
        }
}

