// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.AccessCode2JsonTypes;

namespace Example.AccessCode2JsonTypes
{

    public class Location
    {

        [JsonProperty("type")]
        public string Type;

        [JsonProperty("coordinate")]
        public double[] Coordinate;
    }

}
