// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.AccessCode2JsonTypes;

namespace Example.AccessCode2JsonTypes
{

    public class Record
    {

        [JsonProperty("ID")]
        public string ID;

        [JsonProperty("PARENT_RECORD_ID")]
        public string PARENTRECORDID;

        [JsonProperty("PARENT_PAGE_ID")]
        public string PARENTPAGEID;

        [JsonProperty("PARENT_ELEMENT_ID")]
        public string PARENTELEMENTID;

        [JsonProperty("CREATED_DATE")]
        public string CREATEDDATE;

        [JsonProperty("CREATED_BY")]
        public string CREATEDBY;

        [JsonProperty("CREATED_LOCATION")]
        public string CREATEDLOCATION;

        [JsonProperty("CREATED_DEVICE_ID")]
        public string CREATEDDEVICEID;

        [JsonProperty("MODIFIED_DATE")]
        public string MODIFIEDDATE;

        [JsonProperty("MODIFIED_BY")]
        public string MODIFIEDBY;

        [JsonProperty("MODIFIED_LOCATION")]
        public string MODIFIEDLOCATION;

        [JsonProperty("MODIFIED_DEVICE_ID")]
        public string MODIFIEDDEVICEID;

        [JsonProperty("text_element")]
        public string TextElement;

        [JsonProperty("my_element1")]
        public object MyElement1;

        [JsonProperty("my_element2")]
        public object MyElement2;
    }

}
