// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using iFormBuilderAPI.Location;

namespace iFormBuilderAPI.Location
{

    public class Location2
    {

        [JsonProperty("type")]
        public string Type;

        [JsonProperty("coordinate")]
        public double[] Coordinate;
    }

}
