// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace iFormBuilderAPI
{
    public class AccessCode : iFormBuilderAPI.IAccessCode
    {
        public string access_token { get; set; }
        public string token_type { get; set; }
        private int _expires;
        public int expires_in
        {
            get{
                return _expires;
            }
            set
            {
                _expires = value;
                codeexpires = DateTime.Now.AddSeconds(_expires);
            }
        }

        private DateTime codeexpires { get; set; }
        public bool isExpired
        {
            get
            {
                return DateTime.Now.Ticks >= codeexpires.Ticks;
            }
        }
    }
}
